---

- name: "Go-Lang | Install dependencies"
  apt:
    pkg: [ 'curl', 'gcc', 'git', 'findutils', 'make', 'rsync', 'tar' ]
    state: present
  register: apt_result
  become: yes
  until: apt_result is success
  retries: 1
  delay: 2

- name: "Go-Lang | Define GOARCH"
  set_fact:
    GOARCH: "amd64"
  when: GOARCH is not defined

- name: "Go-Lang | Define GOOS"
  set_fact:
    GOOS: "linux"
  when: GOOS is not defined
